#!/bin/bash

function scp_to_30() {
        ARGS=( $@ )
        TO_COPY=
        for idx in ${!ARGS[@]}; do [ $idx -eq 1 ] && DEST="${ARGS[$idx]}" || TO_COPY="${ARGS[$idx]} $TO_COPY"; done
	scp -r "$TO_COPY" jenkins@degamhunav30.eso.local:$DEST
}
function scp_from_30() {
        ARGS=( $@ )
	ARG_C=$#
	DEST="${ARGS[$((ARG_C-1))]}"
        for idx in ${!ARGS[@]}; do [ $idx -lt $((ARG_C-1)) ] && scp -r jenkins@degamhunav30.eso.local:${ARGS[$idx]} $DEST; done
}
