#!/bin/bash
log() {
  TAG=$TAG
  [ -z "$COLORS_SET" ] && . $BASHSRC/colors
  [ -z "$LINENR" ] && LINENR=$(printf %04d ${BASH_LINENO[0]})
  [ -z "$SCRIPT" ] && SCRIPT="${BASH_SOURCE[1]}"
  [ -z "$TAG" ] && {
        [ -z "$SCRIPT" ] && TAG="" || TAG=$(basename ${SCRIPT})
  }
  VARS_TO_UNSET="LINENR SCRIPT"
  ## log levels ##
  I="INFO"
  V="VERBOSE"
  D="DEBUG"
  E="ERROR"
  W="WARN"
  INFO=$GREEN
  VERBOSE=$GRAY
  DEBUG=$WHITE
  ERROR=$RED
  WARN=$YELLOW
  [ -z "$LOG_LEVEL" ] && LOG_LEVEL="DEBUG"
  LEVEL=${!1}
  COLOR=${!LEVEL}
  margin() {
      size=$1
      i=0 
      MARGIN=""
      while ((i<size)); do     
          MARGIN="$MARGIN "
          i=$((i+1))
      done
      echo "$MARGIN"
  }
  LEVEL_MAX_LENGTH=7
  LEVEL_LENGTH=${#LEVEL}; diff=$((LEVEL_MAX_LENGTH - LEVEL_LENGTH)); MARGIN_RIGHT=$((diff/2)); MARGIN_LEFT=$(( MARGIN_RIGHT + ( diff%2 ) ));
  LEVEL="$(printf "${GRAY_BOLD}[$(margin $MARGIN_LEFT)${NONE}${COLOR}%s$(margin $MARGIN_RIGHT)${NONE}${GRAY_BOLD}]${NONE}" "${LEVEL}")"
  LEVELS=""
  VARS_TO_UNSET="$VARS_TO_UNSET COLOR LEVEL LEVELS"
  case "$LOG_LEVEL" in
        INFO)
                LEVELS="I E";
                ;;
        VERBOSE)
                LEVELS="I V E W"
                ;;
        DEBUG)
                LEVELS="I V D E W"
                ;;
        ERROR)
                LEVELS="E"
                ;;
        WARN)
                LEVELS="E I W";
                ;;
        QUIET)
                LEVELS=""
                ;;
  esac
  h=':'
  MTAG="$(printf "${WHITE}%10s${NONE}${GRAY_BOLD}${h}${LINENR}${NONE}" "${TAG}")"

  if [ ! -z "$(echo $LEVELS | grep $1)" ]; then
        [ -n $SSH_TTY ] && LOG_DEST=$SSH_TTY || LOG_DEST=/dev/fd/1
        ma=""
        args=( "$@" )
        j=1
        while [ $j -lt $# ]; do
                [[ ${args[j]} =~ ^-(e|-exit) ]] && WITH_EXIT=1 || {
                        ma="${ma}${args[j]} "
                        status=${args[j]}
                }
                j=$((j+1))
        done
        ( printf "    $MTAG $LEVEL  ::  ${COLOR}${ma}${NONE} \n" > $LOG_DEST ) 2> /dev/null || printf "    $MTAG $LEVEL  ::  ${COLOR}${ma}${NONE} \n" > /dev/fd/1
  fi
  [ $WITH_EXIT ] && [ "$LEVEL" = "E" ] && [[ $status =~ ^[0-9]+ ]] && exit $status
  VARS_TO_UNSET="$VARS_TO_UNSET LOG_DEST ma args j status VARS_TO_UNSET"
  for v in $VARS_TO_UNSET; do unset $v; done; unset v
}